### ISSUE TITLE
tuner.search won't work in Kerastuner 1.0.3 and 1.0.4

### ISSUE THREAD

**Issue by daniellarin99** [keras-team/keras-tuner#600]
**Describe the bug**
Using the newer versions of kerastuner (1.0.3 and 1.0.4) throws following error while using the search function for keras_tuner.tuners.Sklearn:

```python
Traceback (most recent call last):
  File "/app/testing_cnn.py", line 50, in <module>
    tuner.search(x, y)
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/tuners/sklearn_tuner.py", line 145, in search
    return super().search(X, y, sample_weight=sample_weight, groups=groups)
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/engine/base_tuner.py", line 176, in search
    self.run_trial(trial, *fit_args, **fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras_tuner/tuners/sklearn_tuner.py", line 163, in run_trial
    if isinstance(model, sklearn.pipeline.Pipeline):
AttributeError: module 'sklearn' has no attribute 'pipeline'
```

**To Reproduce**
Following code reproduces this error:
```python
import numpy as np
from keras_tuner import HyperParameters, Objective
from keras_tuner.oracles import BayesianOptimization
from keras_tuner.tuners import RandomSearch, Sklearn
from sklearn import ensemble, linear_model, tree


def build_model_sklearn(hp):
    model_type = hp.Choice("model_type", ["random_forest", "ridge", "decision_tree"])
    if model_type == "random_forest":
        with hp.conditional_scope("model_type", "random_forest"):
            model = ensemble.RandomForestRegressor(
                n_estimators=hp.Int("n_estimators", 10, 50, step=10),
                max_depth=hp.Int("max_depth", 3, 10),
            )
    elif model_type == "ridge":
        with hp.conditional_scope("model_type", "ridge"):
            model = linear_model.Ridge(alpha=hp.Float("alpha", 1e-3, 1, sampling="log"))
    elif model_type == "decision_tree":
        with hp.conditional_scope("model_type", "decision_tree"):
            model = tree.DecisionTreeRegressor(
                max_depth=hp.Int("max_depth", 50, 100, step=10)
            )
    else:
        raise ValueError("Unrecognized model_type")
    return model


def tuner_sklearn(
    build_model: HyperParameters, model_name: str
):
    return Sklearn(
        oracle=BayesianOptimization(
            objective=Objective("score", "max"),
            max_trials=10,
        ),
        hypermodel=build_model,
        directory=model_name,
    )


x = np.array([[10, 20, 30, 40], [20, 30, 40, 50], [30, 40, 50, 60], [40, 50, 60, 70], [50, 60, 70, 80], [60, 70, 80, 90]])
y = np.array([50, 60, 70, 80, 90, 100])

tuner = tuner_sklearn(
    build_model_sklearn,
    model_name='test',
)

tuner.search(x, y)
``` 
**Expected behavior**
In version 1.0.2 this code (with changing keras_tuner to kerastuner) won't throw an exception and hyperparametertuning just works.

**Additional context**
Using kt.SklearnTuner instead of kt.tuners.Sklearn won't fix this problem (this function was renamed in version 1.0.3).

**Comment by haifeng-jin** [comment]
@daniellarin99 Thanks for the issue.
Adding `import sklearn.pipeline` would temporarily fix the problem.
We will fix this in the next release.
