### ISSUE TITLE
from keras_tuner.engine import trial fails with Import Error on v1.4.1

### ISSUE THREAD

**Issue by singhniraj08** [keras-team/keras-tuner#947]
**Describe the bug**
 
Running `from keras_tuner.engine import trial` fails with ImportError on v1.4.1 but works on v1.3.5

**To Reproduce**
 
https://colab.research.google.com/gist/singhniraj08/f14f52fe0ca5f633a8919104088137df/keras-tuner_engine_trail-import-error.ipynb

**Expected behavior**
 
Import should work successfully

**Additional context**
 
Error Log:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-58e1e05063e7> in <cell line: 1>()
----> 1 from keras_tuner.engine import trial

ImportError: cannot import name 'trial' from 'keras_tuner.engine' (/usr/local/lib/python3.10/dist-packages/keras_tuner/engine/__init__.py)

**Would you like to help us fix it?**
